# install CMake
- name: Download CMake
  get_url:
    url: https://cmake.org/files/v{{ CMAKE_VERSION }}/cmake-{{ CMAKE_VERSION }}.{{ CMAKE_BUILD_VERSION }}-linux-x86_64.sh
    dest: /opt/cmake-{{ CMAKE_VERSION }}.{{ CMAKE_BUILD_VERSION }}-linux-x86_64.sh
    validate_certs: false

# - name: Extract CMake archive
#   unarchive:
#     dest: /opt
#     src: /opt/elfutils-{{ ELFUTILS_VERSION }}.tar.bz2
#     creates: /opt/elfutils-{{ ELFUTILS_VERSION }}
#     copy: no

- name: install CMake
  shell: |
    mkdir /opt/cmake
    cd /opt
    sh cmake-{{ CMAKE_VERSION }}.{{ CMAKE_BUILD_VERSION }}-linux-x86_64.sh --prefix=/usr --skip-license
    rm -f cmake-{{ CMAKE_VERSION }}.{{ CMAKE_BUILD_VERSION }}-linux-x86_64.sh